### ISSUE TITLE
use a more professional theme

### ISSUE THREAD

**Issue by maximz** [PrincetonUSG/homepage#1]
One that stood out to me: https://html5up.net/phantom (CC licensed). premium version is at pixelarity.

Also here are some free stock photos from unsplash that may be useful as backgrounds:

* princeton: ![c_tff2uxgdc-roman-mager](https://cloud.githubusercontent.com/assets/141115/22665686/a6cd4f2a-ec83-11e6-94e5-437c907aec97.jpg)
* useful apps for students: ![e3uy4k7ooyk-davide-cantelli](https://cloud.githubusercontent.com/assets/141115/22665693/ab9a2b72-ec83-11e6-9251-203134b649db.jpg)
* developers: ![zmraooybtlq-artem-sapegin](https://cloud.githubusercontent.com/assets/141115/22665698/b1d247cc-ec83-11e6-9bce-663e52e5aa1a.jpg)

**Comment by nicholaspad** [comment]
Here's a new design (4 years later): https://github.com/PrincetonUSG/homepage/pull/2
